In [1]:
import pandas as pd

In [2]:
## series
## one-dimensional array

data=pd.Series([1,2,3,4,5])
print(data)
print(type(data))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
## create a series from dict

data={'a':1,'b':2}
series_dict=pd.Series(data)
series_dict

a    1
b    2
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
## DataFrame
## create a data frame from dict of lst

data={
    'Name':['abc','cde','efg'],
    'Age':[25,45,23],
    'City':['Pune','Jaipur','Mumbai']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

  Name  Age    City
0  abc   25    Pune
1  cde   45  Jaipur
2  efg   23  Mumbai
<class 'pandas.core.frame.DataFrame'>

In [6]:
import numpy as np
np.array(df)

array([['abc', 25, 'Pune'],
       ['cde', 45, 'Jaipur'],
       ['efg', 23, 'Mumbai']], dtype=object)

In [12]:
## create a dataframe from a lst of dict

data=[
    {'Name':'abc','age':25,'City':'Pune'},
    {'Name':'cde','age':45,'City':'Jaipur'},
    {'Name':'efg','age':23,'City':'Mumbai'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

  Name  age    City
0  abc   25    Pune
1  cde   45  Jaipur
2  efg   23  Mumbai
<class 'pandas.core.frame.DataFrame'>

In [27]:
file=pd.read_csv('Details.csv')
file.head(5)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [28]:
file.tail(5)

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7      -3         2     Clothing  Hankerchief         COD
1496  B-25757    3151     -35         7     Clothing     Trousers         EMI
1497  B-25973    4141    1698        13  Electronics     Printers         COD
1498  B-25698       7      -2         1     Clothing  Hankerchief         COD
1499  B-25993    4363     305         5    Furniture       Tables         EMI

In [29]:
## Accessing data from dataframe
file

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [13]:
df['Name']

0    abc
1    cde
2    efg
Name: Name, dtype: object

In [14]:
df.loc[0][0]

C:\Users\ABRAR\AppData\Local\Temp\ipykernel_25140\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'abc'

In [15]:
df.iloc[0][2]

C:\Users\ABRAR\AppData\Local\Temp\ipykernel_25140\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Pune'

In [16]:
## Accesing Specified element
df['Name']

0    abc
1    cde
2    efg
Name: Name, dtype: object

In [17]:
df.at[1,'age']

np.int64(45)

In [18]:
df.at[1,"Name"]

'cde'

In [19]:
## Acccesing a specified element using iat
df.iat[2,2]

'Mumbai'

In [20]:
## data manipulation using DatFrame

df['Salary']=[20000,65000,40000]
df

  Name  age    City  Salary
0  abc   25    Pune   20000
1  cde   45  Jaipur   65000
2  efg   23  Mumbai   40000

In [21]:
df.drop('Salary',axis=1,inplace=True)
df

  Name  age    City
0  abc   25    Pune
1  cde   45  Jaipur
2  efg   23  Mumbai

In [22]:
## increase Age
df['age']=df['age']+1
df

  Name  age    City
0  abc   26    Pune
1  cde   46  Jaipur
2  efg   24  Mumbai

In [25]:
df.drop(1,inplace=True)
df

  Name  age    City
2  efg   24  Mumbai

In [33]:
print('File Summary :')
file.describe()

File Summary :

            Amount      Profit     Quantity
count  1500.000000  1500.00000  1500.000000
mean    291.847333    24.64200     3.743333
std     461.924620   168.55881     2.184942
min       4.000000 -1981.00000     1.000000
25%      47.750000   -12.00000     2.000000
50%     122.000000     8.00000     3.000000
75%     326.250000    38.00000     5.000000
max    5729.000000  1864.00000    14.000000