In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('my_file (1).csv')
df

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [3]:
df.describe()

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [5]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [6]:
df.drop(columns=['All Time Peak','Peak','Artist','Tour title','Ref.'],inplace=True)

In [7]:
df.columns=df.columns.str.strip()

In [8]:
df.columns.tolist()

['Rank',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Year(s)',
 'Shows',
 'Average gross']

In [9]:
df.columns=df.columns.str.replace('\xa0',' ')

In [10]:
df['Actual gross']=df['Actual gross'].replace(r'\D','',regex=True).astype(int)

In [11]:
df['Adjusted gross (in 2022 dollars)']=df['Adjusted gross (in 2022 dollars)'].replace(r'\D','',regex=True).astype(int)

In [12]:
df['Average gross']=df['Average gross'].replace(r'\D','',regex=True).astype(int)

In [13]:
print(repr(df.columns.tolist()))

['Rank', 'Actual gross', 'Adjusted gross (in 2022 dollars)', 'Year(s)', 'Shows', 'Average gross']

In [14]:
df

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Year(s),Shows,Average gross
0,1,780000000,780000000,2023–2024,56,13928571
1,2,579800000,579800000,2023,56,10353571
2,3,411000000,560622615,2008–2009,85,4835294
3,4,397300000,454751555,2018–2019,156,2546795
4,5,345675146,402844849,2018,53,6522173
5,6,305158363,388978496,2012,88,3467709
6,7,280000000,381932682,2008–2009,131,2137405
7,7,257600000,257600000,2023–2024,41,6282927
8,9,256084556,312258401,2016,49,5226215
9,10,250400000,309141878,2015,85,2945882
10,11,229100000,283202896,2013–2014,132,1735606
11,12,227400000,295301479,2009–2011,203,1118227
12,13,204000000,251856802,2014–2015,151,1350993
13,14,200000000,299676265,2002–2005,325,615385
14,15,194000000,281617035,2006,60,3233333
15,16,184000000,227452347,2013–2014,142,1295775
16,17,170000000,213568571,2012–2013,98,1734694
17,18,169800000,207046755,2015–2016,82,2070732
18,19,167700000,204486106,2016–2017,121,1385950
19,20,150000000,185423109,2013–2014,86,1744186

In [15]:
df.columns=df.columns.str.replace(r'[()]','',regex=True)

In [21]:
repr(df['Years'][0])

"'2023–2024'"

In [20]:
df.columns.tolist()

['Rank',
 'Actual gross',
 'Adjusted gross in 2022 dollars',
 'Years',
 'Shows',
 'Average gross',
 'Duration',
 'start_year',
 'end_year']

In [34]:
df['Years']=df['Years'].replace(r'[^0-9]','-',regex=True)
def duration(Years):
    if '-' in Years:
        start_year=int(Years.split('-')[0])
        end_year=int(Years.split('-')[1])
        duration=end_year-start_year+1
    else:
        duration=1
        start_year=int(Years)
        end_year=int(Years)
    return pd.Series([duration,start_year,end_year])

df[['Duration','start_year','end_year']]=df['Years'].apply(duration)

In [35]:
df

,Rank,Actual gross,Adjusted gross in 2022 dollars,Years,Shows,Average gross,Duration,start_year,end_year
0,1,780000000,780000000,2023-2024,56,13928571,2,2023,2024
1,2,579800000,579800000,2023,56,10353571,1,2023,2023
2,3,411000000,560622615,2008-2009,85,4835294,2,2008,2009
3,4,397300000,454751555,2018-2019,156,2546795,2,2018,2019
4,5,345675146,402844849,2018,53,6522173,1,2018,2018
5,6,305158363,388978496,2012,88,3467709,1,2012,2012
6,7,280000000,381932682,2008-2009,131,2137405,2,2008,2009
7,7,257600000,257600000,2023-2024,41,6282927,2,2023,2024
8,9,256084556,312258401,2016,49,5226215,1,2016,2016
9,10,250400000,309141878,2015,85,2945882,1,2015,2015
10,11,229100000,283202896,2013-2014,132,1735606,2,2013,2014
11,12,227400000,295301479,2009-2011,203,1118227,3,2009,2011
12,13,204000000,251856802,2014-2015,151,1350993,2,2014,2015
13,14,200000000,299676265,2002-2005,325,615385,4,2002,2005
14,15,194000000,281617035,2006,60,3233333,1,2006,2006
15,16,184000000,227452347,2013-2014,142,1295775,2,2013,2014
16,17,170000000,213568571,2012-2013,98,1734694,2,2012,2013
17,18,169800000,207046755,2015-2016,82,2070732,2,2015,2016
18,19,167700000,204486106,2016-2017,121,1385950,2,2016,2017
19,20,150000000,185423109,2013-2014,86,1744186,2,2013,2014

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Rank                            20 non-null     int64
 1   Actual gross                    20 non-null     int64
 2   Adjusted gross in 2022 dollars  20 non-null     int64
 3   Years                           20 non-null     object
 4   Shows                           20 non-null     int64
 5   Average gross                   20 non-null     int64
 6   Duration                        20 non-null     int64
 7   start_year                      20 non-null     int64
 8   end_year                        20 non-null     int64
dtypes: int64(8), object(1)
memory usage: 1.5+ KB

In [39]:
df.drop(columns='Years',inplace=True)

In [40]:
df

,Rank,Actual gross,Adjusted gross in 2022 dollars,Shows,Average gross,Duration,start_year,end_year
0,1,780000000,780000000,56,13928571,2,2023,2024
1,2,579800000,579800000,56,10353571,1,2023,2023
2,3,411000000,560622615,85,4835294,2,2008,2009
3,4,397300000,454751555,156,2546795,2,2018,2019
4,5,345675146,402844849,53,6522173,1,2018,2018
5,6,305158363,388978496,88,3467709,1,2012,2012
6,7,280000000,381932682,131,2137405,2,2008,2009
7,7,257600000,257600000,41,6282927,2,2023,2024
8,9,256084556,312258401,49,5226215,1,2016,2016
9,10,250400000,309141878,85,2945882,1,2015,2015
10,11,229100000,283202896,132,1735606,2,2013,2014
11,12,227400000,295301479,203,1118227,3,2009,2011
12,13,204000000,251856802,151,1350993,2,2014,2015
13,14,200000000,299676265,325,615385,4,2002,2005
14,15,194000000,281617035,60,3233333,1,2006,2006
15,16,184000000,227452347,142,1295775,2,2013,2014
16,17,170000000,213568571,98,1734694,2,2012,2013
17,18,169800000,207046755,82,2070732,2,2015,2016
18,19,167700000,204486106,121,1385950,2,2016,2017
19,20,150000000,185423109,86,1744186,2,2013,2014