In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
## datset --> tips
df=sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [6]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [7]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [8]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [9]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [10]:
# dependent and independent features
X=df[['total_bill', 'tip', 'sex', 'smoker', 'day','size']]
y=df['time']
X

     total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [11]:
type(y)

pandas.core.series.Series

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [13]:
X_train.head()

     total_bill   tip   sex smoker  day  size
58        11.24  1.76  Male    Yes  Sat     2
1         10.34  1.66  Male     No  Sun     3
2         21.01  3.50  Male     No  Sun     3
68        20.23  2.01  Male     No  Sat     2
184       40.55  3.00  Male    Yes  Sun     2

In [14]:
## feature encoding(Label encoding and one-hot encoding)
from sklearn.preprocessing import LabelEncoder as LE

le1=LE()
le2=LE()
le3=LE()

In [15]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
y_train=le3.fit_transform(y_train.values)

In [16]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0])

In [17]:
X_train.head()

     total_bill   tip  sex  smoker  day  size
58        11.24  1.76    1       1  Sat     2
1         10.34  1.66    1       0  Sun     3
2         21.01  3.50    1       0  Sun     3
68        20.23  2.01    1       0  Sat     2
184       40.55  3.00    1       1  Sun     2

In [18]:
X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])
y_test=le3.transform(y_test.values)

In [19]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0])

In [20]:
## one hot encoding -- column transformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [21]:
ct=ColumnTransformer(transformers=[('Onehot',OneHotEncoder(drop='first'),[4])],remainder='passthrough')

In [22]:
X_train=ct.fit_transform(X_train)

In [23]:
X_test=ct.transform(X_test)

In [24]:
X_train

array([[1., 0., 0., ..., 1., 1., 2.],
       [0., 1., 0., ..., 1., 0., 3.],
       [0., 1., 0., ..., 1., 0., 3.],
       ...,
       [1., 0., 0., ..., 1., 0., 2.],
       [0., 0., 1., ..., 0., 0., 6.],
       [0., 1., 0., ..., 1., 0., 2.]], shape=(183, 8))

In [25]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score, classification_report
print('Accuracy Score = ', accuracy_score(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))

Accuracy Score =  0.9672131147540983

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.95      0.98        43
           1       0.90      1.00      0.95        18

    accuracy                           0.97        61
   macro avg       0.95      0.98      0.96        61
weighted avg       0.97      0.97      0.97        61